apiVersion: v1
kind: Secret
metadata:
  name: harbor-docker-config
  namespace: tekton-pipelines
  annotations:
    tekton.dev/docker-0: "http://192.168.65.254:90"
type: kubernetes.io/basic-auth
stringData:
  username: "admin"
  password: "harbor123"
