apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: llmops-abtest-gateway-build
  namespace: tekton-pipelines
spec:
  params:
    - name: GIT_REPO
      type: string
    - name: IMAGE
      type: string
  workspaces:
    - name: source
  volumes:
    - name: docker-config
      secret:
        secretName: harbor-docker-config
    - name: git-basic-auth-2
      secret:
        secretName: git-basic-auth-2

  steps:
    - name: clone-repo
      image: alpine/git
      script: |
        cd /workspace/source
        git clone http://$(cat /credentials/username):$(cat /credentials/password)@$(params.GIT_REPO) .
      volumeMounts:
        - name: git-basic-auth-2
          mountPath: /credentials
          readOnly: true

    - name: kaniko-build
      image: gcr.io/kaniko-project/executor:debug
      computeResources:
        requests:
          memory: 2Gi
          cpu: 1000m
        limits:
          memory: 4Gi
          cpu: 1000m
      script: |
        VERSION_TAG=$(grep 'tag:' /workspace/source/helm/values.yaml | awk '{print $2}' | tr -d '"')
        echo "VERSION_TAG=$VERSION_TAG"

        /kaniko/executor \
          --dockerfile=/workspace/source/Dockerfile \
          --context=/workspace/source \
          --destination=$(params.IMAGE):$VERSION_TAG \
          --insecure
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
