apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: tekton-listener-abtest-gateway
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-sa
  triggers:
    - name: gitlab-trigger-abtest-gateway
      bindings:
        - ref: gitlab-trigger-binding-abtest-gateway
      template:
        ref: gitlab-trigger-template-abtest-gateway
