apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: gitlab-trigger-binding-abtest-gateway
  namespace: tekton-pipelines
spec:
  params:
    - name: GIT_REPO
      value: "192.168.65.254:8080/root/llm-gateway.git"
    - name: IMAGE
      value: "192.168.65.254:90/library/llm-gateway"
