apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: gitlab-trigger-template-abtest-v1
  namespace: tekton-pipelines
spec:
  params:
    - name: GIT_REPO
    - name: IMAGE
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: llm-abtest-v1-build-run-
      spec:
        pipelineRef:
          name: llm-build-pipeline-abtest-v1
        params:
          - name: GIT_REPO
            value: $(tt.params.GIT_REPO)
          - name: IMAGE
            value: $(tt.params.IMAGE)
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 1Gi
